#!/bin/bash
# used for backing up entire linux systems. In order for this to work,
# the target machine's SSH daemon must allow root to login using a public key
# without password authentication. See https://unix.stackexchange.com/questions/92123/rsync-all-files-of-remote-machine-over-ssh-without-root-user/92397#92397 and https://wiki.archlinux.org/title/rsync#Automated_backup_with_SSH

#retrieve CLI flags
while getopts u:h: flag
do
    case "${flag}" in
        h) host=${OPTARG};;
    esac
done

BACKUP_PATH=$(pwd)/system-backups/$host
LOGS_DIR=./.logs/$host
LOGFILE=$LOGS_DIR/$host-$( date '+%F_%H:%M:%S' ).log

# make backup directory if it doesn't exist
mkdir -p $BACKUP_PATH
mkdir -p $LOGS_DIR 

rsync -aAXHv --progress --stats --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/home/peaster/.cache"} -e ssh root@$host:/ $BACKUP_PATH --log-file=$LOGFILE 
